# Generated by Django 5.1.6 on 2025-03-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_rename_memebers_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="members",
            name="joined_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="members",
            name="phone",
            field=models.IntegerField(null=True),
        ),
    ]
